# Generated by Django 3.2.7 on 2021-12-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.CharField(max_length=255),
        ),
    ]
